name = "Hugo Portfolio"
license = "MIT"
licenselink = "https://github.com/dombyte/hugo-portfolio/blob/main/LICENSE"
description = "A highly customizable and mobile first Hugo template for personal portfolio with dark theme."
homepage = "https://github.com/dombyte/hugo-portfolio/"
tags = ["Responsive", "Portfolio", "Personal","Dark Theme"]
features = ["Dark Theme","Responsive"]
min_version = "0.74.3"

[author]
  name = "Dominik Wenninger"
  homepage = "itsdom.org"


[original]
  name = "Alexa Portfolio"
  Repo = "https://github.com/Bonzdev/alexa-portfolio"
  name = "bona tua"
  homepage = "bonzdev.com"
  license = "MIT"
  